# Model Configuration for Production Environment
models:
  primary:
    name: "facebook/opt-125m"
    type: "github"
    context_length: 2048
    temperature: 0.7
    max_tokens: 150
    timeout: 30
    retry:
      max_attempts: 3
      backoff_factor: 2

  fallback:
    - name: "gpt2"
      type: "github"
      context_length: 1024
      temperature: 0.7
      max_tokens: 150
      timeout: 30
      retry:
        max_attempts: 2
        backoff_factor: 1.5
    
    - name: "distilgpt2"
      type: "github"
      context_length: 1024
      temperature: 0.7
      max_tokens: 150
      timeout: 30
      retry:
        max_attempts: 2
        backoff_factor: 1.5

circuit_breaker:
  failure_threshold: 3
  recovery_timeout: 300
  error_types:
    - ModelRuntimeError
    - TokenLimitError
    - TimeoutError

validation:
  response_schema:
    required:
      - content
      - confidence
      - error
    types:
      content: str
      confidence: float
      error: "str | None"
    constraints:
      confidence:
        min: 0.0
        max: 1.0

memory_management:
  max_batch_size: 50
  cleanup_interval: 300
  context_ttl: 3600

monitoring:
  metrics:
    - error_rate
    - latency_p95
    - memory_usage
    - token_usage
  alerts:
    error_rate_threshold: 0.05
    latency_threshold: 2000
    memory_threshold: 0.9 