models:
  primary:
    provider: github
    model: claude-3-sonnet-20240229
    temperature: 0.7
    max_tokens: 4000
    timeout_seconds: 30

  fallback:
    - provider: github
      model: gpt-4
      temperature: 0.7
      max_tokens: 2000
      timeout_seconds: 20
    
    - provider: github
      model: gpt-3.5-turbo
      temperature: 0.7
      max_tokens: 1000
      timeout_seconds: 10

circuit_breaker:
  failure_threshold: 3
  recovery_timeout: 300  # 5 minutes
  error_types:
    - ModelRuntimeError
    - TokenLimitError
    - TimeoutError

response_validation:
  required_fields:
    - content
    - confidence
    - error
  confidence_threshold: 0.7
  max_retries: 2

logging:
  level: INFO
  handlers:
    - type: file
      filename: logs/model_operations.log
    - type: console
      level: WARNING 