# YNAB API Configuration
YNAB_API_KEY = "your_ynab_api_key_here"
YNAB_BUDGET_ID = "your_default_budget_id"

# OpenAI Configuration
OPENAI_API_KEY = "your_openai_api_key_here"

# App Settings
DEBUG_MODE = false
CACHE_TTL = 300  # seconds
MAX_MESSAGE_HISTORY = 10 